### ISSUE TITLE
Rails 5.1.5 fails but 5.1.4 worked.

### ISSUE THREAD

**Issue by skunkworker** [alekseyl/rails_select_on_includes#11]
Rails 5.1.4 worked just fine. I'm currently trying to track down the changes. It seems like 5.1.5 is calling `instance.arel` where 5.1.4 didn't.

**Comment by alekseyl** [comment]
OK, I'll look for it.

**Comment by alekseyl** [comment]
fixed in version 5.1.5.1, plz try it and give a feedback
now it's two branches for 5.1.4 and 5.1.5 rails version...
and 5.2 is next to come.

**Comment by alekseyl** [comment]
added 5.2.rc1 support also ( 5.2.0.1 version )

**Comment by skunkworker** [comment]
awesome, thanks @alekseyl
