### ISSUE TITLE
Can we have comma only separator?

### ISSUE THREAD

**Issue by mlt** [alekseyl/rails_select_on_includes#15]
I'm talking about https://github.com/alekseyl/rails_select_on_includes/blob/08f94294a87e611c53d393b54254e1bef2841442/lib/rails_select_on_includes.rb#L35

As of now expressions like
```
  @stuff = Mymodel.join(my_arel.join_sources)
    .select('some.stuff,
    other.stuff')
```
are broken if there is no space after `some.stuff,`.

**Comment by alekseyl** [comment]
I'll look to it

**Comment by alekseyl** [comment]
I think such 
      .split(/,[\s$]*/) would be enough

**Comment by alekseyl** [comment]
done in all gem versions
