### ISSUE TITLE
Appears to break in Rails 5.2.1

### ISSUE THREAD

**Issue by aaronchi** [alekseyl/rails_select_on_includes#16]

**Comment by alekseyl** [comment]
did you use appropriate version of a gem? there are lots of them for different rails versions.

**Comment by aaronchi** [comment]
I was running this in a Rails 5.2.0 app and upgrading Rails to 5.2.1 caused some regressions. Removing this gem fixed them.

I assume something changed in 5.2.1 that broke the functionality.

**Comment by agirling** [comment]
I also found a regression using Rails 5.2.1 with rails_select_on_includes-5.2.0.3.  I am receiving a new, empty object when I am expecting a persisted one.

Curiously, this only occurs when I try and order by the included model:
```
Inventory::Model.includes(:category).order('inventory_categories.id').first

SQL (9.6ms)  SELECT  `inventory_models`.* FROM `inventory_models` LEFT OUTER JOIN `inventory_categories` ON `inventory_categories`.`id` = `inventory_models`.`category_id` ORDER BY inventory_categories.id  LIMIT 1

=> #<Inventory::Model:0x0000000008d5b6c0
id: nil,
category_id: nil,
...
```

Without the gem installed, I am receiving the expected result:
```
Inventory::Model.includes(:category).order('inventory_categories.id').first

 SQL (9.9ms)  SELECT  `inventory_models`.`id` AS t0_r0, `inventory_models`.`category_id` AS t0_r1, `inventory_categories`.`id` AS t1_r0 FROM `inventory_models` LEFT OUTER JOIN `inventory_categories` ON `inventory_categories`.`id` = `inventory_models`.`category_id` ORDER BY inventory_categories.id LIMIT 1

=> #<Inventory::Model:0x000000000c965b98
id: 65,
category_id: 1
...
```

Lastly, here is the gem working on Rails 5.2.0:
```
Inventory::Model.includes(:category).order('inventory_categories.id').first

 SQL (13.5ms)  SELECT  `inventory_models`.`id` AS t0_r0, `inventory_models`.`category_id` AS t0_r1, `inventory_categories`.`id` AS t1_r0 FROM `inventory_models` LEFT OUTER JOIN `inventory_categories` ON `inventory_categories`.`id` = `inventory_models`.`category_id` ORDER BY inventory_categories.id LIMIT 1

=> #<Inventory::Model:0x000000000c12f780
id: 41,
category_id: 1,
...
```
Please let me know if I can provide any additional data to help diagnose this regression.

**Comment by alekseyl** [comment]
It's more than enough. I'll try to fix it as soon as possible.

**Comment by alekseyl** [comment]
Hmm strange, I upgraded to rails 5.2.1 tests uncovered an error like calling private method, but after fix - tests run smoothly, can you try it from the rails_5.2.1 branch? I didn't go deeper in the sources so may be problem stills, check plz.

**Comment by alekseyl** [comment]
and also if one of the problem is fixed, but the order problems stays - plz let me know, and reopen issue as a different one.

**Comment by alekseyl** [comment]
reproduced order issue, covered with test, - now its working ( branch 5.2.1 ) plz check.

PS wanna output SQL - use my gem niceql ;)

**Comment by agirling** [comment]
@alekseyl Thank you.  I'll bump up to 5.2.1 and report back.

Also, your gem looks interesting!

**Comment by agirling** [comment]
@alekseyl tested against branch 5.2.1, all good here!

**Comment by alekseyl** [comment]
thanks @agirling,  I'll deliver new version ASAP.

**Comment by alekseyl** [comment]
done in version 5.2.1
