### ISSUE TITLE
Support rails 6?

### ISSUE THREAD

**Issue by ikepon** [alekseyl/rails_select_on_includes#17]
I use rails_select_on_includes gem on Rails 6 and raise `NoMethodError (undefined method 'testval' for nil:NilClass)` when I did these commands:

```console
irb(main):001:0> Post.create(title: 'title', body: 'body')

irb(main):002:0> post = Post.includes(:comments).select("posts.*, 1 as testval").where(id: [1,2]).first
   (1.1ms)  SELECT sqlite_version(*)
  Post Load (0.2ms)  SELECT posts.*, 1 as testval FROM "posts" WHERE "posts"."id" IN (?, ?) ORDER BY "posts"."id" ASC LIMIT ?  [["id", 1], ["id", 2], ["LIMIT", 1]]
  Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
=> #<Post id: 1, title: "title", body: "body", created_at: "2019-09-03 08:52:17", updated_at: "2019-09-03 08:52:17">

irb(main):003:0> post.comments.first.testval
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `testval' for nil:NilClass)
```

Do you support Rails6?

If you want to try to check, I created sample app:
https://github.com/ikepon/sample_app_for_rails6

And try these commands:

```console
git clone git@github.com:ikepon/sample_app_for_rails6.git

cd sample_app_for_rails6

bundle

bin/rails db:create db:migrate

yarn install --check-files

bin/rails c
```

and do these commands on rails console:

```console
Post.create(title: 'title', body: 'body')

post = Post.includes(:comments).select("posts.*, 1 as testval").where(id: [1,2]).first

post.comments.first.testval
```

**Comment by alekseyl** [comment]
Yep, I should. But I can't give you an ETA on that. I'm totally occupied right now with my working activities and family duties :(.

**Comment by ikepon** [comment]
Thank you for your reply.

I understand your circumstances.
If you have time, I'd be happy to support Rails6.

While waiting for your correction, I consider another method.

**Comment by nicovak** [comment]
I had issues with this too on rails 6.

I just removed this gem and replaced `eager_load` and others kind of stuff (`includes`, etc) with `joins` and It works. Ok it's not the best solution but It works.

It's kinda hard to support this fix while updating rails, we had issue with pretty much each version so I think I should stop rely on this.

Many thanks by the way.

**Comment by sasha-id** [comment]
https://github.com/alekseyl/rails_select_on_includes/pull/18

**Comment by alekseyl** [comment]
OK, I'll review and try to release support ASAP

**Comment by alekseyl** [comment]
Big thnx to Alex-klepa, tests for rails 6 also passing, so I think its working. New version 6.0.0 is released!

**Comment by alekseyl** [comment]
> It's kinda hard to support this fix while updating rails, we had issue with pretty much each version so I think I should stop rely on this.

I'm trully sorry for letting you guys down. This was my first starred gem, so I'll continue its support anyway. Just fire issues earlier :).

**Comment by ikepon** [comment]
Thanks for fixing 😄
