### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by pasivuorio** [alekseyl/rails_select_on_includes#2]
Any plans to provide Rails 5 support for this gem? It solved the problem on Rails 4, but when trying to switch into Rails 5.1.0, it gives following error:

An ActiveRecord::StatementInvalid occurred in modelname#search:
PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $4

Any help would be appreciated.

**Comment by alekseyl** [comment]
I'll look for it in a week :)

**Comment by alekseyl** [comment]
Actually it works in rails 5, can you post here result of to_sql of your query? It looks like they downgrade algorythm.

I've got this on rails 5:

User.limit(10).includes( :student ).joins(:students).select( 'users.*', "students.name as st_name" ).to_sql

"SELECT  users.*, students.name as st_name FROM \"users\" INNER JOIN \"students\" ON \"students\".\"user_id\" = \"users\".\"id\" LIMIT 10"

And on rails 4.2:

Buyer.limit(1).includes(:orders).joins(:orders).select('users.*, orders.delivery_info').to_sql

translates to:
"SELECT users.*, orders.delivery_info, \"users\".\"id\" AS t0_r0, \"users\".\"email\" AS t0_r1, \"users\".\"encrypted_password\" AS t0_r2, \"users\".\"reset_password_token\" AS t0_r3, \"users\".\"reset_password_sent_at\" AS t0_r4, \"users\".\"remember_created_at\" AS t0_r5, \"users\".\"sign_in_count\" AS t0_r6, \"users\".\"current_sign_in_at\" AS t0_r7, \"users\".\"last_sign_in_at\" AS t0_r8, \"users\".\"current_sign_in_ip\" AS t0_r9, \"users\".\"last_sign_in_ip\" AS t0_r10, \"users\".\"created_at\" AS t0_r11, \"users\".\"updated_at\" AS t0_r12, \"users\".\"name\" AS t0_r13, \"users\".\"confirmation_token\" AS t0_r14, \"users\".\"confirmed_at\" AS t0_r15, \"users\".\"confirmation_sent_at\" AS t0_r16, \"users\".\"unconfirmed_email\" AS t0_r17, \"users\".\"role\" AS t0_r18, \"users\".\"type\" AS t0_r19, \"users\".\"status\" AS t0_r20, \"users\".\"pricing_coefficient\" AS t0_r21, \"users\".\"working_hours\" AS t0_r22, \"users\".\"distribution_center_id\" AS t0_r23, \"users\".\"admin_comment\" AS t0_r24, \"users\".\"manager\" AS t0_r25, \"users\".\"pledge_tax\" AS t0_r26, \"users\".\"user_type_id\" AS t0_r27, \"users\".\"min_opt\" AS t0_r28, \"users\".\"distributor\" AS t0_r29, \"users\".\"fca\" AS t0_r30, \"orders\".\"id\" AS t1_r0, \"orders\".\"buyer_id\" AS t1_r1, \"orders\".\"delivery_type\" AS t1_r2, \"orders\".\"delivery_info\" AS t1_r3, \"orders\".\"status\" AS t1_r4, \"orders\".\"created_at\" AS t1_r5, \"orders\".\"updated_at\" AS t1_r6, \"orders\".\"buyer_gets_delivery\" AS t1_r7, \"orders\".\"price_kopeks\" AS t1_r8, \"orders\".\"in_cart\" AS t1_r9, \"orders\".\"payment_data\" AS t1_r10, \"orders\".\"delivery_zone_id\" AS t1_r11, \"orders\".\"notified\" AS t1_r12, \"orders\".\"world_delivery_zone_id\" AS t1_r13, \"orders\".\"veterinary_certificates_count\" AS t1_r14, \"orders\".\"fast_payment\" AS t1_r15, \"orders\".\"processed_id\" AS t1_r16, \"orders\".\"deleted_at\" AS t1_r17, \"orders\".\"comment\" AS t1_r18, \"orders\".\"started_at\" AS t1_r19, \"orders\".\"supplier_must_confirm\" AS t1_r20, \"orders\".\"buyer_must_confirm\" AS t1_r21, \"orders\".\"buyer_must_pay\" AS t1_r22, \"orders\".\"supplier_must_confirm_delivery\" AS t1_r23, \"orders\".\"supplier_must_deliver\" AS t1_r24, \"orders\".\"delivery_region_price_kopecks\" AS t1_r25, \"orders\".\"region_address\" AS t1_r26, \"orders\".\"opt\" AS t1_r27, \"orders\".\"prev_buyer_get_date\" AS t1_r28, \"orders\".\"distributor_fca\" AS t1_r29, \"orders\".\"moscow_delivery_desired_date\" AS t1_r30 FROM \"users\" INNER JOIN \"orders\" ON \"orders\".\"buyer_id\" = \"users\".\"id\" AND \"orders\".\"deleted_at\" IS NULL WHERE \"users\".\"type\" IN ('Buyer', 'Guest') AND \"users\".\"id\" IN (101)"

**Comment by alekseyl** [comment]
Done, now version are splitted to 0.4 for rails 4.x and 0.5 for rails 5.x

in rails 5 you need to rewrite your gem file
gem 'rails_select_on_include', '~> 0.5.0'
