### ISSUE TITLE
Breaks on subqueries with AS

### ISSUE THREAD

**Issue by tkalliom** [alekseyl/rails_select_on_includes#6]
If the `select` contains multiple instances of the keyword `AS`, mapping of attributes fails.

```
> User.includes(:comments).where(id: 1).order("comments.updated_at").select("(SELECT COUNT(*) FROM replies AS r WHERE r.user_id = users.id) AS reply_count").first.attributes
=> {"id"=>1, "email"=>"someone@example.com", "r WHERE r.user_id = users.id) as reply_count"=>nil}
```
Subqueries without `AS` work fine.

**Comment by alekseyl** [comment]
OK I'll will soon add your PR, after some refactoring and test coverage

**Comment by alekseyl** [comment]
which rails and gem version? I just test this query:

( SELECT MAX( warriors_count ) as maxw FROM ( SELECT COUNT(id) AS warriors_count FROM combatants GROUP BY war_group_id ) as t ) as biggest_coalition
  

It's actually work fine.

Upd. And this is strange cause Regexp works as you describe

Upd2, forgot that conditions must be specified ON children relation.
